#=====================================================================#
#                             Table of Contents                       #
#=====================================================================#
#     1       #               Plugins                                 #
#     2       #               Information                             #
#     3       #               Head links                              #
#     4       #               Archives & Collections                  #
#     5       #               Asset Optimizers                        #
#     6       #               Include/Exclude                         #
#=====================================================================#

#======================================================================
#                               Plugins
#======================================================================

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-minifier
  - jekyll_dynamic_assets
  #- jekyll-purge-css

#======================================================================
#                             Information
#======================================================================

url: "https://mumarshahbaz.github.io"
baseurl: "/Oscilloscope-Online-V2"
title: Oscilloscope Online
description: "Oscilloscope Online is a powerful web serial plotter for electronics, data visualization, and custom signal analysis. Fast, customizable, and feature-rich."
lang: "en"
keywords: [oscilloscope, online, web serial, plotter, electronics, data visualization, signal analysis, customisation, open source]
author: M. Umar Shahbaz
image: assets/img/icon.png
logo: assets/img/icon.svg

#======================================================================
#                              Shareing
#======================================================================

share-presets:
  intro:
    class: intro
    sites:
      - Facebook
      - X
      - LinkedIn
      - Reddit
      - WhatsApp
      - Telegram
      - Messenger
      - Devto
      - Mail
  end:
    class: end
    sites:
      - Facebook
      - X
      - LinkedIn
      - Reddit
      - WhatsApp
      - Telegram
      - Messenger
      - Devto
      - Mail

#======================================================================
#                             Head links
#======================================================================

dynamic_assets:
  absolute: true
  source:
    base: /assets
    uPlot: https://cdn.jsdelivr.net/npm/uplot/dist
    SVG_Plotter_Deprecated: https://cdn.jsdelivr.net/gh/MUmarShahbaz/SVG-Plotter-deprecated@dist
    html2canvas: https://cdnjs.cloudflare.com/ajax/libs/html2canvas/1.4.1
  master:
   - master.css
   - status.min.js::defer-js
   - bootstrap.min.js::defer-js
  formats:
    defer-js: <script defer src="%s"></script>
  presets:
    uPlot:
     - uPlot<</uPlot.min.css
     - uPlot<</uPlot.iife.min.js

#======================================================================
#                        Archives & Collection
#======================================================================

collections:
  pages:
    output: true

#======================================================================
#                          Asset Optimizers
#======================================================================

jekyll-minifier:
  compress_javascript: false

PurgeCSS:
  content: [./_site/**/*.html, ./_site/**/*.js]
  css: [./_site/assets/styles/*.css]
  output: ./_site/assets/styles/

#======================================================================
#                              Include/Exclude
#======================================================================

exclude:
  - .bundle/
  - .github/
  - .jekyll-cache/
  - .vscode/
  - assets/ts/
  - dev_scripts/
  - node_modules/
  - temp/
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - README.md
  - tsconfig.json