url: "https://mumarshahbaz.github.io"
baseurl: "/Oscilloscope-Online-V2"
title: Oscilloscope Online 2
description: A web serial plotter with a huge variety of features and customisation
author: M. Umar Shahbaz
logo: 

collections:
  _pages:
    output: true

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll_dynamic_assets

exclude:
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock

dynamic_assets:
  absolute: true
  source:
    assets: https://cdn.jsdelivr.net/gh/MUmarShahbaz/Oscilloscope-Online-V2@assets
  master:
   - assets<</bootstrap.min.css
  formats:
    defer-js: <script defer src="%s"></script>